name: Deployment pipeline for redux-anecdotes

defaults:
  run:
    working-directory: ./part11/redux-anecdotes

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  complete_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./part11/redux-anecdotes
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: -patch

      - name: Push to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: ./part11/redux-anecdotes
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'redux-anecdotes-louis'
          heroku_email: 'penalva.louis@gmail.com'
          procfile: 'web: npm run start-prod'
          #healthcheck: 'https://redux-anecdotes-louis.herokuapp.com/health'
          #checkstring: 'ok'
          #rollbackonhealthcheckfailed: true

      - name: Slack notification success
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack notification failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
