name: Deployment pipeline

defaults:
  run:
    working-directory: ./part11/full-stack-open-pokedex

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          working-directory: ./part11/full-stack-open-pokedex
          runTests: false
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory:
            ./part11/full-stack-open-pokedex
            # we have already installed all dependencies above
          install: false
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Push to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: ./part11/full-stack-open-pokedex
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'pokedex-louis'
          heroku_email: 'penalva.louis@gmail.com'
          procfile: 'web: npm run start-prod'
          healthcheck: 'https://pokedex-louis.herokuapp.com//health'
          checkstring: 'ok'
